POST http://localhost:8080/api/patients
Content-Type: application/json

{
  "documentNumber": "12345678",
  "fullName": "Juan Pérez",
  "email": "juan@example.com",
  "phone": "999999999"
}
###

POST http://localhost:8080/api/appointments
Content-Type: application/json

{
  "patientId": 1,
  "scheduledAt": "2025-12-01T10:30:00",
  "reason": "Control general"
}

###
GET http://localhost:8080/api/appointments

####
PATCH http://localhost:8080/api/appointments/1/cancel
