spring:
  application:
    name: order-service
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: health,info

clients:
  user:
    url: http://user-service:8081
  product:
    url: http://product-service:8082
